name: Deployment pipeline

on:
  push:
    branches:
      - dev

jobs:
  backend_tests:
    runs-on: ubuntu-20.04
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: cd backend && npm install

      - name: Check style
        run: cd backend && npm run test
        env:
          ORS_API_KEY: ${{ secrets.ORS_API_KEY }}
